#include <gtest/gtest.h>

#include "SingleDetectionDatasetParser_test.cpp"
#include "Parser_test.cpp"
#include "NeuralNetworkParser_test.cpp"
#include "LineBreakParser_test.cpp"
#include "ImageLocationParser_test.cpp"
#include "ImageParserWithSizing_test.cpp"
#include "DetectionDataParser_test.cpp"
#include "DetectionDataParser_test.cpp"
#include "Factory/DetectionResultFactory_test.cpp"
#include "DetectionResultParser_test.cpp"
#include "ClassProbabilityParser_test.cpp"
#include "Factory/ClassificationResultFactory_test.cpp"
#include "Factory/BoundingBoxFactory_test.cpp"
#include "BoundingBoxParser_test.cpp"
#include "ClassificationResultParser_test.cpp"
#include "LayerParsing/ActivationLayerParser_test.cpp"
#include "LayerParsing/ConvolutionalLayerParser_test.cpp"
#include "LayerParsing/FlattenLayerParser_test.cpp"
#include "LayerParsing/DenseLayerParser_test.cpp"
#include "LayerParsing/MaxPoolLayerParser_test.cpp"
#include "Factory/ActivationLayerFactory_test.cpp"
#include "Factory/ConvolutionalLayerFactory_test.cpp"
#include "Factory/DenseLayerFactory_test.cpp"
#include "Factory/DenseLayerFactory_test.cpp"

